force-app/main/default/objects/nvl_obj_airport__c/nvl_obj_airport__c.object-meta.xml
<CustomObject>
    <label>Airport</label>
    <nameField>
        <label>Airport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/nvl_obj_airport__c/fields/nvl_fld_IATACode__c.field-meta.xml
<CustomField>
    <fullName>nvl_fld_IATACode__c</fullName>
    <label>IATA Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/nvl_obj_airport__c/fields/nvl_fld_latitude__c.field-meta.xml
<CustomField>
    <fullName>nvl_fld_latitude__c</fullName>
    <label>Latitude</label>
    <precision>8</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/nvl_obj_airport__c/fields/nvl_fld_longitude__c.field-meta.xml
<CustomField>
    <fullName>nvl_fld_longitude__c</fullName>
    <label>Longitude</label>
    <precision>11</precision>
    <required>true</required>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/nvl_obj_flight__c/nvl_obj_flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <displayFormat>FLT-{000}</displayFormat>
        <label>Flight Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/nvl_obj_flight__c/fields/nvl_fld_arrivalAirport__c.field-meta.xml
<CustomField>
    <fullName>nvl_fld_arrivalAirport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Arrival airport</label>
    <referenceTo>nvl_obj_airport__c</referenceTo>
    <relationshipLabel>Flights (Arrival airport)</relationshipLabel>
    <relationshipName>ArrivalFlights</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/nvl_obj_flight__c/fields/nvl_fld_departureAirport__c.field-meta.xml
<CustomField>
    <fullName>nvl_fld_departureAirport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure airport</label>
    <referenceTo>nvl_obj_airport__c</referenceTo>
    <relationshipLabel>DepartureFlights</relationshipLabel>
    <relationshipName>Flights</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/nvl_obj_flight__c/fields/nvl_fld_flightDistance__c.field-meta.xml
<CustomField>
    <fullName>nvl_fld_flightDistance__c</fullName>
    <label>Flight distance</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Nvl_cls_nuvolarFlightsGateway_Test.cls
@isTest
public with sharing class Nvl_cls_nuvolarFlightsGateway_Test {
    @TestSetup
    private static void makeData(){
        List<nvl_obj_Airport__c> airportList = new List<nvl_obj_Airport__c>();
        nvl_obj_Airport__c airport1 = new nvl_obj_Airport__c();
        airport1.Name = 'Aeropuerto Internacional de la Región de Murcia';
        airport1.nvl_fld_IATACode__c = 'RMU';
        airport1.nvl_fld_latitude__c = 37.803;
        airport1.nvl_fld_longitude__c = -1.125;
        airportList.add(airport1);

        nvl_obj_Airport__c airport2 = new nvl_obj_Airport__c();
        airport2.Name = 'Aeropuerto de Alicante-Elche';
        airport2.nvl_fld_IATACode__c = 'ALC';
        airport2.nvl_fld_latitude__c = 38.2822;
        airport2.nvl_fld_longitude__c = -0.558156;
        airportList.add(airport2);

        insert airportList;

        List<nvl_obj_flight__c> flightsList = new List<nvl_obj_flight__c>();
        nvl_obj_flight__c flight = new nvl_obj_flight__c();
        flight.nvl_fld_arrivalAirport__c = airport1.Id;
        flight.nvl_fld_departureAirport__c = airport2.Id;
        flight.nvl_fld_flightDistance__c = 72.82;
        flightsList.add(flight);

        insert flightsList;
    }

    @isTest
    private static void testGetAllAirports(){
        Test.startTest();
        List<nvl_obj_Airport__c> airportList = Nvl_cls_nuvolarFlightsGateway.getAllAirports();
        Test.stopTest();
        Assert.areEqual(2, airportList.size(), 'Airport list have an incorrect size.');
    }

    @isTest
    private static void testGetAllFlights(){
        nvl_obj_flight__c testFlight = [SELECT Id,nvl_fld_flightDistance__c FROM nvl_obj_flight__c LIMIT 1];
        Test.startTest();
        List<nvl_obj_flight__c> flightList = Nvl_cls_nuvolarFlightsGateway.getAllFlights();
        Test.stopTest();
        Assert.areEqual(flightList.get(0).nvl_fld_flightDistance__c, testFlight.nvl_fld_flightDistance__c, 'Wrong flight selected, distance is incorrect');
    }
}