force-app/main/default/objects/nvl_obj_airport__c/nvl_obj_airport__c.object-meta.xml
<CustomObject>
    <label>Airport</label>
    <nameField>
        <label>Airport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/nvl_obj_airport__c/fields/nvl_fld_IATACode__c.field-meta.xml
<CustomField>
    <fullName>nvl_fld_IATACode__c</fullName>
    <label>IATA Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/nvl_obj_airport__c/fields/nvl_fld_latitude__c.field-meta.xml
<CustomField>
    <fullName>nvl_fld_latitude__c</fullName>
    <label>Latitude</label>
    <precision>8</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/nvl_obj_airport__c/fields/nvl_fld_longitude__c.field-meta.xml
<CustomField>
    <fullName>nvl_fld_longitude__c</fullName>
    <label>Longitude</label>
    <precision>11</precision>
    <required>true</required>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/nvl_obj_flight__c/nvl_obj_flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <displayFormat>FLT-{000}</displayFormat>
        <label>Flight Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/nvl_obj_flight__c/fields/nvl_fld_arrivalAirport__c.field-meta.xml
<CustomField>
    <fullName>nvl_fld_arrivalAirport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Arrival airport</label>
    <referenceTo>nvl_obj_airport__c</referenceTo>
    <relationshipLabel>Flights (Arrival airport)</relationshipLabel>
    <relationshipName>ArrivalFlights</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/nvl_obj_flight__c/fields/nvl_fld_departureAirport__c.field-meta.xml
<CustomField>
    <fullName>nvl_fld_departureAirport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure airport</label>
    <referenceTo>nvl_obj_airport__c</referenceTo>
    <relationshipLabel>DepartureFlights</relationshipLabel>
    <relationshipName>Flights</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/nvl_obj_flight__c/fields/nvl_fld_flightDistance__c.field-meta.xml
<CustomField>
    <fullName>nvl_fld_flightDistance__c</fullName>
    <label>Flight distance</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Nvl_cls_nuvolarFlightsGateway.cls
public with sharing class Nvl_cls_nuvolarFlightsGateway {

    /*
    * Method that search all Airports in the BBDD
    * return List of Airports in the BBDD
    */
    public static List<nvl_obj_airport__c> getAllAirports(){
        return [SELECT Id,Name, nvl_fld_IATACode__c, nvl_fld_latitude__c, nvl_fld_longitude__c 
                FROM nvl_obj_airport__c];
    }

    /*
    * Method that search all Flights in the BBDD
    * return List of Flights in the BBDD
    */
    public static List<nvl_obj_flight__c> getAllFlights(){
        return [SELECT Id,Name,nvl_fld_arrivalAirport__c, nvl_fld_departureAirport__c, nvl_fld_flightDistance__c,nvl_fld_arrivalAirport__r.nvl_fld_IATACode__c,nvl_fld_departureAirport__r.nvl_fld_IATACode__c 
                FROM nvl_obj_flight__c 
                ORDER BY Name ASC];
    }
}